### ISSUE TITLE
jenkins pipeline doesnt abort if error building docker image

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/kubernetes-workflow#17]
For another reason that I don't understand yet the swift example fails to build when running on openshift.  That aside the pipeline only failed when the tag was attempted which is slightly misleading, it would be good if the pipeline was aborted as soon as the docker build failed.  

Full jenkins log..

```
Started by user anonymous
Cloning the remote Git repository
remote: Counting objects
remote: Compressing objects
Receiving objects
Resolving deltas
Updating references
Checking out Revision 86b42ad288121bf79d5d3aef4c7b05906aa90f39 (refs/remotes/origin/master)
First time build. Skipping changelog.
[Workflow] Allocate node : Start
Still waiting to schedule task
ebda11651c1f9 is offline
Running on ebda11651c1f9 in /home/jenkins/workspace/workspace/node-app-1
[Workflow] node {
[Workflow] git
Cloning the remote Git repository
remote: Counting objects
remote: Compressing objects
Receiving objects
Resolving deltas
Updating references
Checking out Revision 86b42ad288121bf79d5d3aef4c7b05906aa90f39 (refs/remotes/origin/master)
First time build. Skipping changelog.
[Workflow] stage: canary release
Entering stage canary release
Proceeding
[Workflow] fileExists
[Workflow] writeFile
[Workflow] echo
NOTE: until we support pushing tags to remote repos with correct secrets lets default to use the short commit sha as the version
[Workflow] sh
[node-app-1] Running shell script
+ git rev-parse --short HEAD
[Workflow] readFile
[Workflow] buildImage
Creating tar from path: ..Building image:node-app-1 from path:..
Step 0 : FROM fabric8/swift:2.2-SNAPSHOT-onbuild
[91m# Executing 3 build triggers
[0m
Trigger 0, RUN mkdir -p /usr/src/app
Step 0 : RUN mkdir -p /usr/src/app
---> Using cache
Trigger 1, COPY . /usr/src/app
Step 0 : COPY . /usr/src/app
Trigger 2, RUN swift build --chdir /usr/src/app
Step 0 : RUN swift build --chdir /usr/src/app
---> Running in 2514847125e1
[91mswift-build: error: [0m
[91mYour source structure is not supported due to invalid sources layout: /usr/src/app. There should be no source files under: /usr/src/app.
[0m
[Workflow] tagImage
Tagging image:node-app-1 with tag:86b42ad.
[Workflow] } //node
[Workflow] Allocate node : End
[Workflow] End of Workflow
io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/images/node-app-1/tag?tag=86b42ad&force=false&repo=172.30.1.228:5000/default/node-app-1. Status:404. Message: Not Found. Body: could not find image: no such id: node-app-1
at io.fabric8.docker.client.impl.OperationSupport.requestFailure(OperationSupport.java:266)
at io.fabric8.docker.client.impl.OperationSupport.assertResponseCodes(OperationSupport.java:250)
at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:202)
at io.fabric8.docker.client.impl.ImageTag.withTagName(ImageTag.java:82)
at io.fabric8.docker.client.impl.ImageTag.withTagName(ImageTag.java:33)
at io.fabric8.kubernetes.workflow.TagImageStepExecution$1.call(TagImageStepExecution.java:47)
at io.fabric8.kubernetes.workflow.TagImageStepExecution$1.call(TagImageStepExecution.java:41)
at hudson.remoting.UserRequest.perform(UserRequest.java:121)
at hudson.remoting.UserRequest.perform(UserRequest.java:49)
at hudson.remoting.Request$2.run(Request.java:326)
at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at hudson.remoting.Engine$1$1.run(Engine.java:69)
at java.lang.Thread.run(Thread.java:745)
at ......remote call to ebda11651c1f9(Native Method)
at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
at hudson.remoting.Channel.call(Channel.java:781)
at io.fabric8.kubernetes.workflow.TagImageStepExecution.run(TagImageStepExecution.java:41)
at io.fabric8.kubernetes.workflow.TagImageStepExecution.run(TagImageStepExecution.java:28)
at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:136)
at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:112)
at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:75)
at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:68)
at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
at io.fabric8.kubernetes.workflow.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-workflow/WEB-INF/lib/kubernetes-workflow.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:284)
at io.fabric8.kubernetes.workflow.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-workflow/WEB-INF/lib/kubernetes-workflow.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:33)
at io.fabric8.kubernetes.workflow.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-workflow/WEB-INF/lib/kubernetes-workflow.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:283)
at performCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/performCanaryRelease.groovy:16)
at WorkflowScript.run(WorkflowScript:14)
at Unknown.Unknown(Unknown)
at ___cps.transform___(Native Method)
at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:69)
at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)
at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)
at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
at com.cloudbees.groovy.cps.Next.step(Next.java:58)
at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:145)
at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:106)
at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:274)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:74)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:181)
at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE
```

**Comment by iocanel** [comment]
The failure to abort is a general workflow issue. Maybe bumping to the latest version will fix the issue. 

Now regarding the swift issue the docker build fails. The job should barf on this. I'll need to have a look.
