### ISSUE TITLE
cannot build java projects on a multi-node cluster

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/kubernetes-workflow#26]
end up with this stack trace when try the camel-cdi example for doing CI/CD:

http://pastebin.com/yJbnn3tk

output of master node:
http://pastebin.com/q1mcQkNZ

Node0:
http://pastebin.com/cCiN8MZ7

Node1:
http://pastebin.com/qVXMuuZN

Node2:
http://pastebin.com/jtZHTZsc

Node3:
http://pastebin.com/nPf9FdiN

Node4:
http://pastebin.com/7q7T8YVi

Namespace that I'm running (fuse):
http://pastebin.com/cRdmVDKS

Jenkins pod:
http://pastebin.com/b581FfZD

What other info you need?

**Comment by rawlingsj** [comment]
I've just tested this on the beast (3 nod cluster) and got the same issue when using kubernetes.pod()..

```
Started by user anonymous <http://jenkins.cd.origin.fabric8.io/user/null>
[Workflow] Allocate node : Start
Running on 10f7d69732de6 in /home/jenkins/workspace/workspace/gosupervise
[Workflow] node {
[Workflow] stage: canary release
Entering stage canary release
Proceeding
[Workflow] git
Cloning the remote Git repository
remote: Counting objects
remote: Compressing objects
Receiving objects
Resolving deltas
Updating references
Checking out Revision 0b7abd5e0662d9a34f3967694e7926e04fedfe04 (refs/remotes/origin/master)
First time build. Skipping changelog.
[Workflow] Run build steps as a Kubernetes Pod : Start
[Workflow] Run build steps as a Kubernetes Pod : End
[Workflow] } //node
[Workflow] Allocate node : End
[Workflow] End of Workflow
java.lang.IllegalStateException: No node found for pod:10f7d69732de6
	at io.fabric8.kubernetes.workflow.KubernetesFacade.getNodeOfPod(KubernetesFacade.java:162)
	at io.fabric8.kubernetes.workflow.KubernetesFacade.createPod(KubernetesFacade.java:127)
	at io.fabric8.kubernetes.workflow.PodStepExecution.start(PodStepExecution.java:66)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:112)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at io.fabric8.kubernetes.workflow.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-workflow/WEB-INF/lib/kubernetes-workflow.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:122)
	at io.fabric8.kubernetes.workflow.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-workflow/WEB-INF/lib/kubernetes-workflow.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.workflow.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-workflow/WEB-INF/lib/kubernetes-workflow.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:121)
	at WorkflowScript.run(WorkflowScript:5)
	at Unknown.Unknown(Unknown)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:69)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:40)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:145)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:274)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:74)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:181)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

```

**Comment by iocanel** [comment]
Hopefully, 9a61c7b4e1b1153c0d17b33b1a9aa0e8096401e3 should fix the issue.
