### ISSUE TITLE
Expected HTTP 101 response but was '500 Internal Server Error'

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/kubernetes-workflow#29]
Errors when using kubernetes-pod in a cluster.  This `Expected HTTP 101 response but was '500 Internal Server Error'` seems to happen intermittently when running commands.

```
Started by an SCM change
Connecting to GitHub using rawlingsj/******
Cloning the remote Git repository
remote: Counting objects
remote: Compressing objects
Receiving objects
Resolving deltas
Updating references
Checking out Revision 3f43a6ac84ecee7b9c4e9cbbbab5efb0a738132c (master)
First time build. Skipping changelog.
[Pipeline] Allocate node : Start
Running on 1bc42a384fb24 in /home/jenkins/workspace/workspace/fabric8io/kansible/master
[Pipeline] node {
[Pipeline] stage: canary release
Entering stage canary release
Proceeding
[Pipeline] git
Fetching changes from the remote Git repository
Checking out Revision 3f43a6ac84ecee7b9c4e9cbbbab5efb0a738132c (refs/remotes/origin/master)
First time build. Skipping changelog.
[Pipeline] Run build steps as a Kubernetes Pod : Start
[Pipeline] withKubernetesPod {
[Pipeline] sh
[master] Running shell script
java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[Pipeline] } //withKubernetesPod
[Pipeline] Run build steps as a Kubernetes Pod : End
[Pipeline] } //node
[Pipeline] Allocate node : End
[Pipeline] End of Pipeline
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.waitUntilReady(ExecWebSocketListener.java:120)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.exec(PodOperationsImpl.java:215)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.exec(PodOperationsImpl.java:51)
	at io.fabric8.kubernetes.workflow.KubernetesFacade.exec(KubernetesFacade.java:203)
	at io.fabric8.kubernetes.workflow.PodExecDecorator$1.launch(PodExecDecorator.java:58)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:106)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:57)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:98)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:112)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:75)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
	at WorkflowScript.run(WorkflowScript:12)
	at io.fabric8.kubernetes.workflow.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:123)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:106)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:277)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:77)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:184)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	... 3 more
Finished: FAILURE
```

**Comment by iocanel** [comment]
@rawlingsj: The stack trace doesn't say anything other than that it could open the web socket.

I'll improve the exception handling there in case we can squeeze more info out of it, but I think that our best shot is to read the cabernets master logs, which usually contain more info.

**Comment by rawlingsj** [comment]
ok sounds good @iocanel

**Comment by iocanel** [comment]
An other manifestation of the issue, in the discussion here: https://github.com/fabric8io/kubernetes-client/pull/307

**Comment by rouzwawi** [comment]
Just adding some information about the circumstances in which I see this error:

I have a pod watcher that I set up to watch for events starting at the latest `resourceVersion` i've seen:

```java
client.pods()
    .withResourceVersion(Integer.toString(lastResourceVersion))
    .watch(watcher);
```

If the `lastResourceVersion` is too old, I keep getting the `Expected HTTP 101 response but was '500 Internal Server Error'` on each attempt at setting up the watch.

So far, I've solved this by incrementing the `lastResourceVersion` by `1` each time I see a `ProtocolException`. Eventually the watcher catches up with a version that does not cause the internal server error.

This is not ideal. Also, I'm not completely sure if my assumption about the "version being too old" is a sane one.

**Comment by rawlingsj** [comment]
I've had this another three times consecutively.

**Comment by iocanel** [comment]
In this particular case the issue doesn't seem to be related to "watches" but with "exec". What I see in the server logs is the following error:

Mar 07 10:57:28 origin-master-78z3qe4m origin-master[74624]: E0307 10:57:28.904756   74624 errors.go:62] apiserver received an error that is not an unversioned.Status: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, openshift, openshift.default.svc, openshift.default.svc.cluster.local, origin-master-78z3qe4m.origin.fabric8.io, 10.34.112.97, 172.30.0.1, 192.168.0.4, not origin-node-l3984iun.origin.fabric8.io

The issue appears sporadicly regardless of the client we use (java, oc etc).
