### ISSUE TITLE
cant push to dockerhub "push to official registry: needs to be forced"

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/kubernetes-workflow#30]
I've got a feeling this is a bad error message and its not that we need to force push (actually I dont think there's even an option to), instead my guess is it's not using the docker config secret in the pod.
```
RuntimeException: Failed to push image. Error:Error: Status 403 trying to push repository docker.io/fabric8/kansible to official registry: needs to be forced
```
Full stack trace below.

The jenkinsfile looks like this, @iocanel does the `.withSecret('jenkins-docker-cfg','/home/jenkins/.docker')` look right to you?
```
node{
  stage 'canary release'
  git 'https://github.com/fabric8io/kansible.git'

  kubernetes.pod('buildpod').withImage('fabric8/go-builder')
      .withSecret('jenkins-docker-cfg','/home/jenkins/.docker')
      .withServiceAccount('jenkins').inside {

    retry(3){
      sh 'make bootstrap'
    }

    retry(3){
      sh "cd /go/src/workspace/${env.JOB_NAME} && make build"
    }

    def imageName = 'kansible'
    def tag = 'latest'

    kubernetes.image().withName(imageName).build().fromPath(".")
    kubernetes.image().withName(imageName).tag().inRepository('docker.io/fabric8/'+imageName).force().withTag(tag)
    kubernetes.image().withName('docker.io/fabric8/'+imageName).push().withTag(tag).toRegistry()
  }
}
```
```
[Pipeline] pushImage
Pushing image:docker.io/fabric8/kansible to docker registry.
ERROR: Error: Status 403 trying to push repository docker.io/fabric8/kansible to official registry: needs to be forced

[Pipeline] } //withKubernetesPod
[Pipeline] Run build steps as a Kubernetes Pod : End
[Pipeline] } //node
[Pipeline] Allocate node : End
[Pipeline] End of Pipeline
java.lang.RuntimeException: java.lang.RuntimeException: Failed to push image. Error:Error: Status 403 trying to push repository docker.io/fabric8/kansible to official registry: needs to be forced

	at io.fabric8.kubernetes.workflow.PushImageStepExecution$1.call(PushImageStepExecution.java:102)
	at io.fabric8.kubernetes.workflow.PushImageStepExecution$1.call(PushImageStepExecution.java:50)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to 1bf4536fd1893(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at io.fabric8.kubernetes.workflow.PushImageStepExecution.run(PushImageStepExecution.java:50)
	at io.fabric8.kubernetes.workflow.PushImageStepExecution.run(PushImageStepExecution.java:39)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:112)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:75)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:68)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
	at io.fabric8.kubernetes.workflow.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:350)
	at io.fabric8.kubernetes.workflow.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.workflow.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:349)
	at io.fabric8.kubernetes.workflow.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:355)
	at WorkflowScript.run(WorkflowScript:25)
	at io.fabric8.kubernetes.workflow.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:123)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)
	at sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:106)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:277)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:77)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:184)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to push image. Error:Error: Status 403 trying to push repository docker.io/fabric8/kansible to official registry: needs to be forced

	at io.fabric8.kubernetes.workflow.PushImageStepExecution$1$1.onError(PushImageStepExecution.java:87)
	at io.fabric8.docker.client.impl.EventHandle.onFailure(EventHandle.java:103)
	at io.fabric8.docker.client.impl.EventHandle.onResponse(EventHandle.java:135)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	... 3 more
Finished: FAILURE
```

**Comment by iocanel** [comment]
@rawlingsj: Seems like an invalid auth config issue. 

I think that the main issue with this is that the secret is mounted in the build pod, while the push happens in the jenkins slave. I would remove the secret from the build pod and make sure that the secret is mounted by the slave.

**Comment by rawlingsj** [comment]
@iocanel I've just tested locally the push to dockerhub and got another error (401 Unauthorized).  I can push from the CLI fine.  The jenkins docker secret is in the namespace but I still get the error below.  I'll have a proper dig into it later tonight to get some more information and validate what I've done, maybe  create a test case too.

```
[Pipeline] pushImage
Pushing image:docker.io/fabric8/kansible to docker registry.
The push refers to a repository [docker.io/fabric8/kansible] (len: 1)
ERROR: Post https://registry-1.docker.io/v2/fabric8/kansible/blobs/uploads/: token auth attempt for registry: https://auth.docker.io/token?account=serviceaccount&scope=repository%3Afabric8%2Fkansible%3Apush%2Cpull&service=registry.docker.io request failed with status: 401 Unauthorized
Done.
[Pipeline] } //retry
[Pipeline] Retry the body up to N times : End
[Pipeline] } //withPod
[Pipeline] Run build steps as a Kubernetes Pod : End
[Pipeline] } //node
[Pipeline] Allocate node : End
[Pipeline] End of Pipeline
java.lang.RuntimeException: java.lang.RuntimeException: Failed to push image. Error:Post https://registry-1.docker.io/v2/fabric8/kansible/blobs/uploads/: token auth attempt for registry: https://auth.docker.io/token?account=serviceaccount&scope=repository%3Afabric8%2Fkansible%3Apush%2Cpull&service=registry.docker.io request failed with status: 401 Unauthorized
	at io.fabric8.kubernetes.workflow.PushImageStepExecution$1.call(PushImageStepExecution.java:102)
	at io.fabric8.kubernetes.workflow.PushImageStepExecution$1.call(PushImageStepExecution.java:50)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to ebc8d8a9f48(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at io.fabric8.kubernetes.workflow.PushImageStepExecution.run(PushImageStepExecution.java:50)
	at io.fabric8.kubernetes.workflow.PushImageStepExecution.run(PushImageStepExecution.java:39)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:112)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:76)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:69)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
	at io.fabric8.kubernetes.workflow.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:350)
	at io.fabric8.kubernetes.workflow.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.workflow.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:349)
	at io.fabric8.kubernetes.workflow.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-steps/WEB-INF/lib/kubernetes-steps.jar!/io/fabric8/kubernetes/workflow/Kubernetes.groovy:355)
	at WorkflowScript.run(WorkflowScript:24)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:106)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:277)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:77)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:184)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to push image. Error:Post https://registry-1.docker.io/v2/fabric8/kansible/blobs/uploads/: token auth attempt for registry: https://auth.docker.io/token?account=serviceaccount&scope=repository%3Afabric8%2Fkansible%3Apush%2Cpull&service=registry.docker.io request failed with status: 401 Unauthorized
	at io.fabric8.kubernetes.workflow.PushImageStepExecution$1$1.onError(PushImageStepExecution.java:87)
	at io.fabric8.docker.client.impl.EventHandle.onEvent(EventHandle.java:148)
	at io.fabric8.docker.client.impl.EventHandle.access$000(EventHandle.java:46)
	at io.fabric8.docker.client.impl.EventHandle$1.call(EventHandle.java:114)
	at io.fabric8.docker.client.impl.EventHandle$1.call(EventHandle.java:111)
	at io.fabric8.docker.client.utils.InputStreamPumper.run(InputStreamPumper.java:63)
	... 5 more
Finished: FAILURE
```
