### ISSUE TITLE
 Cannot cast object '[]' with class 'java.util.ArrayList' to class 'java.util.Map' 

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/kubernetes-workflow#33]
I'm getting the error below when trying to run a kubernetes.pod..

To recreate..
```
node{
    kubernetes.pod('buildpod').withImage('fabric8/builder-openshift-client')
      .inside {
        echo 'worked'
    }
}
```

```
[Pipeline] End of Pipeline
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[]' with class 'java.util.ArrayList' to class 'java.util.Map' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.Map()
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:358)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:599)
	at io.fabric8.kubernetes.workflow.Kubernetes.pod(Kubernetes.groovy:41)
	at io.fabric8.kubernetes.workflow.Kubernetes$pod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:76)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
	at WorkflowScript.run(WorkflowScript:6)
```

**Comment by rawlingsj** [comment]
@iocanel I had a look to see if this was a quick fix but I'm not sure what's needed.  Switching [env](https://github.com/fabric8io/kubernetes-workflow/blob/master/kubernetes-steps/src/main/resources/io/fabric8/kubernetes/workflow/Kubernetes.groovy#L41) to use `List<KeyValue> env = new ArrayList<KeyValue>()` instead of `Map<String, String> env = new ArrayList<KeyValue>()` throws another error..

```
ava.lang.UnsupportedOperationException: must specify $class with an implementation of class [Lio.fabric8.kubernetes.workflow.KeyValue;
	at org.jenkinsci.plugins.workflow.structs.DescribableHelper.coerce(DescribableHelper.java:215)
	at org.jenkinsci.plugins.workflow.structs.DescribableHelper.buildArguments(DescribableHelper.java:186)
	at org.jenkinsci.plugins.workflow.structs.DescribableHelper.instantiate(DescribableHelper.java:91)
	at org.jenkinsci.plugins.workflow.steps.StepDescriptor.newInstance(StepDescriptor.java:103)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:133)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:98)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at io.fabric8.kubernetes.workflow.Kubernetes$Pod.inside(/Users/jamesrawlings/fabric8/kubernetes-workflow/kubernetes-steps/target/classes/io/fabric8/kubernetes/workflow/Kubernetes.groovy:122)
	at io.fabric8.kubernetes.workflow.Kubernetes.node(/Users/jamesrawlings/fabric8/kubernetes-workflow/kubernetes-steps/target/classes/io/fabric8/kubernetes/workflow/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.workflow.Kubernetes$Pod.inside(/Users/jamesrawlings/fabric8/kubernetes-workflow/kubernetes-steps/target/classes/io/fabric8/kubernetes/workflow/Kubernetes.groovy:121)
	at WorkflowScript.run(WorkflowScript:2)
	at Unknown.Unknown(Unknown)
	at ___cps.transform___(Native Method)
```

FWIW I'm not sure if this test could ever work with kubernetes workflow but I'm certainly able to recreate the errors from this issue with a unit test if you want a quick way to reproduce it...

``` JAVA
public class PodTest {

    @Rule
    public JenkinsRule r = new JenkinsRule();
    
    @Test public void canStartPod() throws Exception {
        r.createSlave("node-test", null, null);
        WorkflowJob p = r.jenkins.createProject(WorkflowJob.class, "workflow-test");

        p.setDefinition(new CpsFlowDefinition(
                "node{\n" +
                        "    kubernetes.pod('buildpod').withImage('fabric8/builder-openshift-client')\n" +
                        "      .inside {\n" +
                        "        echo 'worked'\n" +
                        "    }\n" +
                        "}"
        ));
        r.assertLogContains("worked", r.assertBuildStatusSuccess(p.scheduleBuild2(0)));
    }
}
```

**Comment by rawlingsj** [comment]
BTW the unit test above needs to be run with preferIPv4Stack
```
mvn test -Djava.net.preferIPv4Stack=true
```

**Comment by iocanel** [comment]
@rawlingsj: I think that I broke it by making it script generator friendly. I'll try to push a fix asap.

**Comment by rawlingsj** [comment]
ok thanks @iocanel, no rush.

Once a fix is there I'll kickoff another release.

**Comment by iocanel** [comment]
@rawlingsj: its not trvial to fix without breaking something else, so please feel free to revert: 105b165af69c10ba5a6197a4e6a97f255f044c73 till I get a real solution.

**Comment by rawlingsj** [comment]
ok will do - thanks @iocanel
