### ISSUE TITLE
java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.Config.<init>

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/kubernetes-workflow#35]
I'm getting the following error during a release and stage of a new nodejs project.
```
[Pipeline] stage: Rolling upgrade Staging
Entering stage Rolling upgrade Staging
Proceeding
[Pipeline] kubernetesApply
[Pipeline] } //node
[Pipeline] Allocate node : End
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.Config.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Boolean;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIJILjava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
	at io.fabric8.openshift.client.OpenShiftConfig.<init>(OpenShiftConfig.java:47)
	at io.fabric8.openshift.client.OpenShiftConfig.<init>(OpenShiftConfig.java:60)
	at io.fabric8.openshift.client.OpenShiftConfig.<init>(OpenShiftConfig.java:38)
	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.isAdaptable(OpenShiftExtensionAdapter.java:46)
	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:55)
	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:33)
	at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:128)
	at io.fabric8.workflow.devops.ApplyStepExecution.createRoutes(ApplyStepExecution.java:190)
	at io.fabric8.workflow.devops.ApplyStepExecution.run(ApplyStepExecution.java:133)
	at io.fabric8.workflow.devops.ApplyStepExecution.run(ApplyStepExecution.java:64)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:112)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:76)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
	at WorkflowScript.run(WorkflowScript:24)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:33)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:22)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:106)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:277)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:77)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:184)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE
```

**Comment by rawlingsj** [comment]
The latest release has the new kubernetes-client https://github.com/fabric8io/kubernetes-workflow/blob/master/pom.xml#L43, is that the issue @iocanel?

**Comment by iocanel** [comment]
@rawlingsj: Seems that the latest release of the kubernetes-client is broken.

**Comment by rawlingsj** [comment]
@iocanel ok - is this something you're looking at?

**Comment by iocanel** [comment]
@rawlingsj: sure

**Comment by iocanel** [comment]
@rawlingsj: The client seems to be fine! We are just using incompatible version between kubernetes-client and openshift-client (the later is brought in fabric8 kubernetes-api). 

So we either need to also upgrade fabric8 to use the latest kubernetes-client stuff, or use dependencyManagement for that.

**Comment by rawlingsj** [comment]
@iocanel ok so new release of fabric8 with the latest kubernetes-client then update kubernetes-workflow with the new fabric8 should do it?

**Comment by iocanel** [comment]
I'll go with the later now, till we short out the release.

**Comment by iocanel** [comment]
@rawlingsj: yeah but till then I'll just add a dependency management (to also protect us in the future, or we are going to hit it very often).

**Comment by rawlingsj** [comment]
@iocanel sounds like a good plan - ok thanks

**Comment by rawlingsj** [comment]
This is resolved with the latest release fabric8/jenkins-docker:2.2.117 which should be available in the next few hours.
